- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/NotificationIconColumns.java
> fix: 修复通知图标上限

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/controlcenter/FlashLight.java
部分机型（如小米10&10S）要调整亮度必须先关闭闪光灯或将闪光灯亮度设为0，再设为指定的值才能生效
具体可参考CIT\LED灯测试
> 部分机型（如小米10&10S）要调整亮度必须先关闭闪光灯或将闪光灯亮度设为0，再设为指定的值才能生效

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/app/OpenByDefaultSetting.kt
此处EzX的hostPackageName和classLoader因未知原因变成了com.miui.contentcatcher的。怀疑是sharedUserId共用一个EzX导致。 修改为使用HookTool。
> fix: OpenByDefaultSetting

- app/src/main/java/com/sevtinge/hyperceiler/utils/ThreadPoolManager.java
修改单例为Double Check的形式，减少进入同步块的开销
> 优化: ThreadPool单例的性能

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/mtb/BypassAuthentication.kt
修复HyperOS上鲁班V6.6.20231111无法通过鉴权的问题
> _P.S.: 看大家在小米10S上用HyperOS非常香，有没有大佬推荐一个小米HyperOS的移植包_
> 修复HyperOS上鲁班V6.6.20231111无法通过鉴权的问题

- app/src/main/java/com/sevtinge/hyperceiler/module/app/Market.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/market/DisablePackageMonitor.kt
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/market.xml
使用root, adb, packageinstaller安装应用后, 应用商店有后台时会上传检查应用更新信息
> feat: 关闭应用商店监控应用安装与卸载

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/externalstorage/DisableFolderCantUse.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/icon/all/IconsFromSystemManager.java
setIcon方法看了下, 原有的 `setIcon(String, StatusBarIcon)` 方法参数变更了, 新参数如图, 导致原有hook失败
在我的xiaomi 12spro上面, 这个方法名称是`shouldBlockDirectoryFromTree`, 做了一下兼容
> fix: hook方法参数变动

- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/dock/HideDock.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/dock/SlideUpOnlyShowDock.kt
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/home_dock.xml
新增 系统桌面-底栏-上滑只展示 Dock 栏
新增 系统桌面-底栏-隐藏 Dock 栏
> 系统桌面-底栏-Dock相关的两个功能

- app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemUI.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/RemoveMiuiMultiWinSwitch.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/UiLockApp.java
- app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/systemui/SystemUIOtherSettings.java
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/system_ui_other.xml
> 新增: 禁用快捷窗口按钮

- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/other/FreeformShortcutMenu.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/other/TasksShortcutMenu.java
仅Pad：使得可以单独强开小窗模式（因为单开多开模式实际上也会开小窗模式）
> 分离Pad上的小窗模式与多开模式

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/SystemLockApp.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/UiLockApp.java
- app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/framework/OtherSettings.java
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/framework_other.xml
一个~~友尽~~实用功能，增加可以通过触摸状态栏不同侧的方式动态选择是否要在退出引导式访问时跳转锁屏，自己用方便，借别人用放心
> 新增：通过使用状态栏不同区域进入引导式访问来决定是否跳转锁屏

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/battery/BatteryHealth.kt
有老外在Tele群里反馈这个功能坏掉了，突然发现是我之前偷的懒。虽然后来他自己弄好了，但我觉得一直用Hardcode不是回事。所以苦学了dexKit然后重写了这部分，完成了这个留了几个月的 `//TODO`
貌似性能有一点影响，安全中心的启动速度变慢了。功能方面已经测试过了，不会有问题的
十分感谢 [@5ec1cff](https://github.com/5ec1cff) 在Tele群给我带来技术支持。
> <Refactor>dexKit 电池健康度

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/sidebar/BlurSecurity.kt
> 重构: 全局侧边栏背景自定义

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemsettings/LanguageMenuShowAllApps.java
> 为所有应用支持管理其不支持的语言

- app/src/main/java/com/sevtinge/hyperceiler/module/app/DownloadsUI.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/downloads/ui/AlwaysShowDownloadLink.java
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/downloads.xml
总是显示下载链接从而允许复制链接 不管是否设置了description 在124.02.28.806005和124.02.28.800006中测试通过  
暂时没有能测试hy2的设备
效果：
> feat - downloads: always show download link

- app/src/main/java/com/sevtinge/hyperceiler/module/app/SecurityCenter/SecurityCenterT.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/other/SimplifyMainFragment.kt
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/security_center_other.xml
手机管家首页移除以下卡片:
- 功能推荐
- 简中用户独享的 “大家都在用”
> 新增: 安全服务-其他-精简手机管家首页

- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Phone/HomeU.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/layout/LayoutRules.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/other/SimplifyMainFragment.kt
- app/src/main/res/xml/home_layout.xml
已知问题待优化
1. 图标、文字大小
2. 编辑图标时的背景位置
3. 在 HyperCeiler 中仅为新版桌面开放设置行列
> 修复: 新版桌面的解锁布局功能

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/other/LockOneHundredPoints.kt
> 修复：锁定100分与禁用优化

- app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemUI/Phone/SystemUiV.java
> fix: Prefs key错误第二次

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/milink/FuckHpplay.java
> fix: FuckHpplay

- app/src/main/java/com/sevtinge/hyperceiler/data/adapter/AppDataAdapter.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/recent/HideRecentCard.kt
- app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/sub/AppPicker.java
- app/src/main/res/layout/fragment_app_picker.xml
fix: 修复 隐藏后台卡片偶现不生效的问题
opt: 优化 选择应用时已选应用置顶
opt: 新增 选择应用界面顶部搜索栏
> opt: AppPicker search and sorting

- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Pad/HomeT.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Pad/HomeU.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Pad/HomeV.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Phone/HomeT.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Phone/HomeU.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Phone/HomeV.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/folder/FolderColumns.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/folder/FolderVerticalSpacing.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/layout/HotSeatsMarginBottom.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/layout/LayoutRules.kt
- app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/app/home/HomeFolderSettings.java
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-in-rID/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-ja-rJP/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-tr-rTR/strings.xml
- app/src/main/res/values-vi-rVN/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/home_folder.xml
- app/src/main/res/xml/home_layout.xml
移动文件夹布局设置，方便统一管理桌面布局
除中文和英文外的翻译项待修正:
- home_folder_width_title
- home_folder_vertical_spacing_desc
> 修复: 文件夹布局功能适配新版桌面

- app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemUI/Phone/SystemUiV.java
> fix: class import

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/getapps/DeviceModify.java
> Fix K80&K80P model

- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Phone/HomeU.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/Home/Phone/HomeV.java
- app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemUI/Phone/SystemUiV.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/layout/LayoutRules.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/Dependency.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/InterfacesImplManager.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/controlcenter/NotificationWeather.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/controlcenter/NotificationWeatherNew.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/model/DualRowSignalHookV.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/model/MobilePublicHookV.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/model/MobileTypeSingle2Hook.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/model/public/MobileClass.kt
天气显示逻辑还有点问题，需要把 oldNotificationWeather 方法的一段代码剪切一下位置
> 修复天气文本框在切换横屏后消失的问题 && 跳转天气应用后自动关闭通知中心

- app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemUI/Phone/SystemUiV.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/lockscreen/NotificationShowOnKeyguard.kt
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/system_ui_lock_screen.xml
> feat: 解锁通知限制

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/dock/DockCustomNew.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/model/DualRowSignalHookV.kt
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/model/MobileTypeSingle2Hook.kt
加回 `access$resetImageWithTintLight` 方法的 hook，没有此方法的系统界面再改为收集监听数据流
> 回滚双排信号图标更新逻辑

- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/AntiQues.java
- app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/network/FlightModeHotSpot.java
unhook classloader hook after used
> unhook classloader hook after used

- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/mtb/BypassAuthentication.kt
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/mtb/IsUserBuild.kt
删掉了旧的hook，看了下hc目前目标适配的版本，删掉应该问题不大，反正os2 a15上能用了（
> 修复os2绕过鲁班鉴权

- library/common-ui/java/main/res/values-zh-rCN/strings_app.xml
- library/common-ui/java/main/res/values/strings_app.xml
- library/common-ui/java/main/res/xml/framework_other.xml
- library/common-ui/java/main/res/xml/prefs_about_contributor.xml
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Pad/SystemFrameworkU.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Pad/SystemFrameworkV.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Phone/SystemFrameworkU.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Phone/SystemFrameworkV.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemframework/BypassForceDownloadui.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemframework/BypassForceMiAppStore.java
代码一团糟，勿怪呜呜（
本来想改成 `findAndHookMethod()` 的，但是没办法正常跑，就这样了嗯（
> feat: 禁用强制使用小米应用商店打开应用商店、禁用强制使用下载管理打开下载页面

- .github/workflows/crowdin.yml
- crowdin.yml
i added 2 folders that were missing in crowdin
> adj: update crowdin files

- library/common-ui/java/main/src/com/sevtinge/hyperceiler/common/prefs/PreferenceHeader.java
> opt: 优化作用域获取

- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/base/pack/systemui/MusicBaseHook.kt
> feat: 在焦点歌词通知中附加音乐软件包名称

- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Pad/SystemFrameworkB.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Phone/SystemFrameworkB.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemframework/DisableLowApiCheckForB.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemframework/DisablePersistent.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/trustservice/DisableMrm.java
修复 HyperOS 3 上的核心破解与 MiTrustService 相关功能，后者应该也包含之前的部分版本修复。
> Fix Something on HyperOS 3

- library/common-ui/java/main/res/values-zh-rCN/strings_app.xml
- library/common-ui/java/main/res/values/strings_app.xml
- library/common-ui/java/main/res/xml/powerkeeper.xml
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Pad/SystemFrameworkB.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/app/SystemFramework/Phone/SystemFrameworkB.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/powerkeeper/ConservativeMillet.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/powerkeeper/GmsDozeFix.java
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemframework/ConservativeMilletFramework.kt
- library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemframework/GMSDozeFixFramework.kt
> fix: GmsDozeFix and ConservativeMillet on OS3 Android 16
