ReChronoRain/HyperCeiler

.github/workflows/android.yml
.github/workflows/androidr.yml
app/src/main/java/com/sevtinge/hyperceiler/module/hook/home/other/HomeMode.java

1. 修复在小米 14 HyperOS 上桌面[深色模式选项错误的问题](https://t.me/cemiuiler/272459)。已在我的小米 14 测试通过，在 MIUI 14 上该开关无效。
2. actions 手动触发时， `github.event.repository.url` 会是 `https://api.github.com/repos/` 开头的链接。现在更改为手动拼接（

Fix dark mode settings for home & fix actions running manually

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/lockscreen/ChargingCVP.kt

相关 issue: 
* https://github.com/GSWXXN/RestoreSplashScreen/issues/34 
* https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/issues/3#issuecomment-1837319082 
* https://github.com/ReChronoRain/HyperCeiler/issues/136
前两个问题是同时使用 [MIUI 遮罩进化](https://github.com/GSWXXN/RestoreSplashScreen) 和开启`锁屏底部显示充电信息`时产生的, 我在调试的时候发现 [HyperCeiler](https://github.com/ReChronoRain/HyperCeiler) 传给 [EzXHelper](https://github.com/KyuubiRan/EzXHelper) 的 ClassLoader 是 `系统桌面` 的 ClassLoader (通过在 pr 的位置捕捉异常并输出 `EzXHelper.hostPackageName` 可以发现这个问题), 在我的测试中指定了正确的 ClassLoader 后就没有问题了.
https://github.com/GSWXXN/RestoreSplashScreen/blob/fd0df958d367a4e50781859893b029ec1e537c3b/app/src/main/java/com/gswxxn/restoresplashscreen/utils/MIUIIconsHelper.kt#L27-L30
可能是我在遮罩模块中使用了 `系统桌面` 的 Context (可以看下上面的代码片段链接), …

尝试修复在部分场景下开启`锁屏底部显示充电信息`时导致系统界面闪退

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/controlcenter/FlashLight.java

小米10S上如果同时操作torch和flashlight节点，会导致闪光灯亮度调整后，再进入相机，无法在相机内正常打开闪光灯，只能重启手机解决。

修复小米10S上同时操作torch和flashlight节点后会导致相机内闪光灯无法打开的问题

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/mtb/BypassAuthentication.kt

(onCreate->onPause->onResume才能打开并不提示鉴权)

修复鲁班V6.0.5及以下版本需要打开后返回再打开一次才能进入的问题

---

app/src/main/res/drawable/ic_hyperceiler_settings_v140.xml

Fix ic_hyperceiler_settings size

---

app/src/main/java/com/sevtinge/hyperceiler/module/app/SecurityCenter.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/other/BypassSimLockMiAccountAuth.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/security_center.xml

跳过开启SIM卡安全保护时需要系统登录小米账号的验证功能

---

app/src/main/java/com/sevtinge/hyperceiler/module/app/Updater.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/updater/AutoUpdateDialog.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/updater.xml

#477 
有人认为屏蔽系统更新可阻止该提示，但是直接屏蔽系统更新会带来许多问题，比如说无法更新新版本。当我们任然需要更新新版本时，还是会遇到该提示。但是开启自动更新会带来更大的问题，比如说掉root；不开启又会弹窗烦人。所以我认为该功能是非常有必要的。
经过我的测试没问题。其他设备未知
1. 硬编码 hook 点，以后更新可能有问题
2. 没写开关的 `summery`
系统更新版本 8.4.7。目前已为最新版

<Add>系统更新关闭“开启自动更新”提示

---

app/src/main/res/values/strings.xml

加入以下磁贴：`颜色反转，流量节省程序，深色主题，单手模式，色彩校正，多用户选择，勿扰`
不会编程，只会改改字符串，如有错误/不恰当的地方各位轻喷（）
部分磁贴不保证所有系统版本可用
（还有部分可添加但没有实际用处/不可用的磁贴，是否需要加入？如闹钟`alarm`，点击长按均无效果，也无法指示目前是否有活动的闹钟）

opt: 补全补全磁铁列表

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/SystemLockApp.java

在部分设备（尤其是Pad上），退出引导式访问后底部手势会失效
经测试发现，发生问题的原因是在hide_gesture_line引发的底部手势线恢复成功前就进行了stopSystemLockTaskMode，相当于先退出引导式访问再恢复手势线，此时手势线功能失效，而先恢复手势线再退出引导式访问则正常。
此PR通过延迟推出引导式访问以等待底部手势线恢复

fix:修复退出引导式访问后可能出现的底部手势失效

---

app/src/main/java/com/sevtinge/hyperceiler/module/base/tool/HookTool.java

修复无法捕获xposed抛出的NoSuchMethodError，周围的代码也都是Throwable

修复安全方法无法捕捉错误

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/SystemLockApp.java

修复引导式访问的解除固定时锁屏功能在日常使用时不生效。bug可能原因：SystemLockApp设置的相关监听没有机会捕捉exit_lock_app_screen值变化，因为它没变

修复引导式访问解除固定时锁屏不生效

---

app/src/main/java/com/sevtinge/hyperceiler/module/app/Telecom.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/telecom/ScamReminderBypass.java
app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/TelecomFragment.java
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_main.xml
app/src/main/res/xml/prefs_set_homepage_entrance.xml
app/src/main/res/xml/telecom.xml

由于**的限制，现在直接拨打类似**21*8#的MMI码会导致无法成功呼出，会有**提示请”在设置中开启呼叫转移“。
本PR则取消此限制。
继续使用此功能，需要在运营商开通呼叫转移业务（因为**的原因，目前呼叫转移业务基本均被取消），方可成功开启呼叫转移，否则依然提示MMI码无效。

允许直接拨打类似**21*8#的MMI码来开启呼叫转移

---

app/src/main/java/com/sevtinge/hyperceiler/ui/base/BaseSettingsActivity.java

Fixed an error that displayed the string like this: Are you sure you want to restart now  XXX ?
instead of : Are you sure you want to restart now XXX?

fix: double spacing in app restart box

---

app/src/main/java/com/sevtinge/hyperceiler/XposedInit.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/network/FlightModeHotSpot.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemsettings/LanguageMenuShowAllApps.java
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/framework_phone.xml

修复“为每个应用管理语言”失效的问题，现在可以对任何应用设置语言了。
飞行模式下可开启热点，暂未作ui绕过，可以使用小艾同学、VPN热点来进行测试，不开启此功能，飞行模式下开热点会返回TETHER_ERROR_INTERNAL_ERROR，开启此功能重启，则不会有此问题。

修复“为每个应用管理语言”失效的问题、飞行模式下可开启热点

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/other/LockOneHundredPoints.kt

禁用体验优化在 MIUI 上不生效
```
[ 2024-07-27T12:47:10.431     1000:  7301:  7301 I/LSPosed-Bridge  ] [HyperCeiler][E][com.miui.securitycenter][LockOneHundredPoints]: Hook Failed: org.luckypray.dexkit.exceptions.NoResultException: No result found for query
at org.luckypray.dexkit.result.BaseDataList.single(DataCollections.kt:137)
at com.sevtinge.hyperceiler.module.hook.securitycenter.other.LockOneHundredPoints.score_delegate$lambda$4$lambda$3(LockOneHundredPoints.kt:42)
at com.sevtinge.hyperceiler.module.hook.securitycenter.other.LockOneHundredPoints.$r8$lambda$gFmh7XfhjPj25cZvE9Ho5o7ncVI(Unknown Source:0)
at com.sevtinge.hyperceiler.module.hook.securitycenter.other.LockOneHundredPoints$$ExternalSyntheticLambda3.dexkit(D8$$SyntheticClass:0)
at …
```

解决 MIUI14 上 "禁用体验优化" 不生效

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/packageinstaller/DisableSafeModelTip.kt

解决 MIUI14 上 "禁用安全守护提示" 不生效
```
[ 2024-07-27T14:11:26.225    10120: 27052: 27052 I/LSPosed-Bridge  ] [HyperCeiler][E][com.miui.packageinstaller][DisableSafeModelTip]: Hook Failed: org.luckypray.dexkit.exceptions.NonUniqueResultException: query did not return a unique result: 2
at org.luckypray.dexkit.result.BaseDataList.single(DataCollections.kt:141)
at com.sevtinge.hyperceiler.module.hook.packageinstaller.DisableSafeModelTip.init$lambda$2(DisableSafeModelTip.kt:36)
at com.sevtinge.hyperceiler.module.hook.packageinstaller.DisableSafeModelTip.$r8$lambda$yelhEkpoRDyekT4KIteVZwshY9s(Unknown Source:0)
at com.sevtinge.hyperceiler.module.hook.packageinstaller.DisableSafeModelTip$$ExternalSyntheticLambda0.dexkit(D8$$SyntheticClass:0)
at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.getElement …
```

解决 MIUI14 上 "禁用安全守护提示" 不生效

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/navigation/NavigationCustom.java
app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/systemui/NavigationSettings.java
app/src/main/res/xml/system_ui_navigation.xml

NavigationHeight 也可以用来控制手势栏高度. 因此, 无论 navigation_mode 为何值, 均开放设置.
同时, 调整hook参数, 解决导航栏设置不生效的问题.
在 miui 14.0.23 上测试正常.

开放 '自定义导航栏' 设置, 并修复导航栏设置不生效

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/network/old/NetworkSpeed.kt

MIUI 状态栏网速默认更新间隔为4s, 显示时未除以时间间隔, 导致网速显示错误.

解决MIUI下网速更新间隔非1秒时网速显示错误

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/device/DisplayHardwareDetail.java
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/system_ui_status_bar_hardware_detail_indicator.xml

功率总显示正值默认开启(和当前默认行为一致). 关闭此选项后, 未充电时功率值显示负数.

状态栏功率添加 '功率总显示正值' 选项

---

app/src/main/assets/tips/tips

The backslash appears in tips within the app, making reading difficult.

Removed "\" from tips

---

app/src/main/java/com/sevtinge/hyperceiler/data/adapter/AppDataAdapter.java
app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemFramework/Phone/SystemFrameworkT.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemframework/CleanProcessTextMenu.java
app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/framework/OtherSettings.java
app/src/main/java/com/sevtinge/hyperceiler/ui/fragment/sub/AppPicker.java
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/framework_other.xml

Editor 等组件中选择文本时会弹出上下文菜单, APP 可在 manifest 中添加 PROCESS_TEXT action 来在此菜单中注册选项.
但 Android 没有提供管理此菜单的方式, 故添加此功能, 用于清理菜单选项.

添加 '清理文本上下文菜单' 功能

---

app/src/main/res/values-ja-rJP/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/framework_other.xml

目前“限制链豁免”的开关打开后，会显示两个“限制链豁免”的选项。因此参照上方选项，将第二个选项的提示文本改为“已选应用”并添加相应描述。

chore: Optimize the prompt text to be consistent with other similar options

---

app/src/main/java/com/sevtinge/hyperceiler/module/app/SecurityCenter/SecurityCenterT.java
app/src/main/java/com/sevtinge/hyperceiler/module/app/SystemFramework/Phone/SystemFrameworkT.java
app/src/main/java/com/sevtinge/hyperceiler/module/hook/securitycenter/other/RemoveSIMLockSuccessDialog.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/security_center_other.xml

移除 SIM 卡安全保护验证成功的弹窗。该弹窗会在自动验证SIM的PIN码后弹出，且无法禁用。

feat: Add a option to remove simlock success dialog

---

app/src/main/java/com/sevtinge/hyperceiler/module/hook/misound/BluetoothListener.java
app/src/main/java/com/sevtinge/hyperceiler/utils/SpatialAudioHelper.kt
app/src/main/res/xml/prefs_set_homepage_entrance.xml

- fix: BluetoothListener in a15
- fix: BluetoothListener 修复首次连接蓝牙耳机时的异常切换
- opt: BluetoothListener 支持记忆并切换沉浸声
- fix: downloads_ui in set_homepage_entrance

修复：耳机自动切换原声 & “下载管理”的主页入口设置

---

app/src/main/res/values/strings.xml

懒得用英文了（）直接用中文写一下pr说明
修了一下“补全磁贴列表”这个功能在os1后期和os2上会把“运行中的应用”磁贴干掉的问题

Fixed missing taskmanager QS tile

---

library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/home/navigation/BackGestureAreaHeight.java

修复：侧滑手势高度修改后，在新版系统桌面上引发返回手势失效问题

fix: BackGesture area height modification fails on new homeApp

---

library/common-ui/java/main/res/values-zh-rCN/strings_app.xml
library/common-ui/java/main/res/values/strings_app.xml
library/common-ui/java/main/res/xml/system_ui_status_bar_music.xml
library/common-ui/src/main/res/layout/focusaodlyric_layout.xml
library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/base/pack/systemui/MusicBaseHook.kt
library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemui/statusbar/icon/v/FocusNotifLyric.kt

- 新增“使用自定义焦点息屏布局”开关，允许用户选择自定义的 AOD 焦点通知布局。
- 为 AOD 模式创建新的布局文件 `focusaodlyric_layout.xml`，其中包含图标和文本。
- 更新 `MusicBaseHook.kt` 以支持新的 AOD 模式，包括：
- 处理图标的亮色和暗色模式。
- 根据 AOD 模式选择不同的 RemoteViews。
- 为 `FocusApi.senddiyFocus` 添加 `pictickerdark` 和 `rvAod` 参数。
- 在中英文语言资源中添加了相应的字符串。

feat: 新增自定义息屏焦点布局

---

library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemui/statusbar/icon/v/FocusNotifLyric.kt

- 优化焦点歌词滚动逻辑，仅当歌词内容变化且与当前 `textView.text` 不同时才更新并重新滚动，避免不必要的重置和闪烁。
- 修复 `startScroll` 调用逻辑，确保在滚动完成后从 `runnablePool` 中移除任务，避免潜在的内存泄漏和重复执行。
- 滚动完成后，将 `is_scrolling` 状态置为 0。
- 新增 `computeScrollDuration` 方法用于计算滚动所需时间。
- 在 `startScroll` 中，滚动完成后移除 `runnablePool` 中的任务引用。

fix: 焦点歌词滚动逻辑优化

---

library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/base/BaseModule.java

Fix #1384
Added a check in BaseModule.init to ensure initialization logic runs only when lpparam.isFirstApplication is true. This prevents redundant initialization for non-primary application processes.

Run init only for first application in BaseModule

---

library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/base/pack/systemui/MusicBaseHook.kt
library/hook/src/main/java/com/sevtinge/hyperceiler/hook/module/hook/systemui/statusbar/icon/all/SwapWiFiAndMobileNetwork.kt

- 在无法加载RemoteView的回退函数里的`FocusApi.baseinfo` 的调用中新增 `content` 参数显示翻译。

feat: 更新灵动岛 API 回退调用添加翻译
